### ISSUE TITLE
Specify requirements for module names & Maven coordinates of compatible implementations

### ISSUE THREAD

**Issue by anthonyvdotbe** [eclipse-ee4j/jakartaee-platform#174]
**Is your feature request related to a problem? Please describe.**
As I see it, implementations of Jakarta EE specifications don't use module names & Maven coordinates correctly/consistently.

I'm especially worried about the current practices of reusing a specification's module name, and adding the `Automatic-Module-Name` attribute to "bundle artifacts" (i.e. JARs that contain both API and implementation classes), since such bundle artifacts are non-modular by definition.

See e.g. [this comment](https://github.com/eclipse-ee4j/mail/issues/409#issuecomment-596132930):
> If the API and implementation are combined in one module, with only the standard
> API exposed, the module should have the name of the standard API, e.g.,
> "jakarta.mail" (although we have no such module here).
> 
> Note that there might be many modules from different implementors with the same
> standard module name. Only the Maven artifact coordinates will distinguish one
> implementation from another.

For example:
* [org.eclipse.persistence:org.eclipse.persistence.jpa:2.7.6](https://repo1.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.jpa/2.7.6/org.eclipse.persistence.jpa-2.7.6.jar) is a non-modular JAR without an `Automatic-Module-Name` attribute, and derived module name `org.eclipse.persistence.jpa`
* [com.sun.mail:jakarta.mail:2.0.0-RC4](https://repo1.maven.org/maven2/com/sun/mail/jakarta.mail/2.0.0-RC4/jakarta.mail-2.0.0-RC4.jar) is a non-modular JAR with `Automatic-Module-Name: jakarta.mail`
* [org.glassfish:jakarta.json:2.0.0-RC2](https://repo1.maven.org/maven2/org/glassfish/jakarta.json/2.0.0-RC2/jakarta.json-2.0.0-RC2.jar) is a non-modular JAR with `Automatic-Module-Name: java.json`
* [org.glassfish:jakarta.json:2.0.0-RC2:module](https://repo1.maven.org/maven2/org/glassfish/jakarta.json/2.0.0-RC2/jakarta.json-2.0.0-RC2-module.jar) is a modular JAR with module name `org.glassfish.java.json`

**Describe the solution you'd like**
The Jakarta EE platform specification should specify requirements on compatible implementations of any of its specifications. Most importantly, it should state that a compatible implementation must:
* use the "reverse DNS" convention and the "root package" to specify the module name. From this it follows that modules must not use a module name in any of the reserved namespaces (java/javax/jakarta), let alone reuse a specification's module name
* at least specify the `Automatic-Module-Name` attribute
* not produce any bundle artifacts, or if they do, specify the `Automatic-Module-Name` attribute with a random value that changes on every release (with the goal of avoiding anyone accidentally relying on it as if it were a module)

Additionally, though I understand this is not something the platform specification can enforce, implementations should be encouraged to adopt the following Maven conventions:
* don't require Maven classifiers for modular JARs: if both a modular and a non-modular JAR need to be produced for some reason, adopt new GAV coordinates and require a classifier such as `legacy` for the non-modular JAR instead
* use dots in groupIds and dashes in artifactIds

Applying these to the examples above:
* [org.eclipse.persistence:org.eclipse.persistence.jpa:2.7.6](https://repo1.maven.org/maven2/org/eclipse/persistence/org.eclipse.persistence.jpa/2.7.6/org.eclipse.persistence.jpa-2.7.6.jar) is not compliant, because it doesn't specify `Automatic-Module-Name`
* [com.sun.mail:jakarta.mail:2.0.0-RC4](https://repo1.maven.org/maven2/com/sun/mail/jakarta.mail/2.0.0-RC4/jakarta.mail-2.0.0-RC4.jar) is not compliant because its module name reuses the specification's module name and is a bundle artifact
* [org.glassfish:jakarta.json:2.0.0-RC2](https://repo1.maven.org/maven2/org/glassfish/jakarta.json/2.0.0-RC2/jakarta.json-2.0.0-RC2.jar) is not compliant because it uses a reserved namespace and is a bundle artifact
* [org.glassfish:jakarta.json:2.0.0-RC2:module](https://repo1.maven.org/maven2/org/glassfish/jakarta.json/2.0.0-RC2/jakarta.json-2.0.0-RC2-module.jar) is not compliant because its module name should just be `org.glassfish.json`. Moreover, it should adopt the proposed Maven conventions by producing the following 2 artifacts instead:
** org.glassfish:jakarta-json:2.0.0-RC2 which is a modular JAR
** org.glassfish:jakarta-json:2.0.0-RC2:legacy which is a non-modular JAR that specifies a random `Automatic-Module-Name` attribute

**Comment by anthonyvdotbe** [comment]
There's been a related [discussion](http://mail.openjdk.java.net/pipermail/jigsaw-dev/2020-April/014425.html) on the OpenJDK mailing lists where Alex Buckley [says](http://mail.openjdk.java.net/pipermail/jigsaw-dev/2020-April/014436.html):
> Every library including its own copy of a standard API is a bug, not a feature.

**Comment by kwsutter** [comment]
Related to Issue #162

**Comment by kwsutter** [comment]
Module naming conventions are being added to the Platform spec via PR #262.

**Comment by lukasj** [comment]
> adopt the following Maven conventions:
> use dots in groupIds and dashes in artifactIds

no, no, let's not change everything again, please! There is https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules already linked from https://jakarta.ee/committees/specification/operations/

**Comment by lukasj** [comment]
and in general `Automatic-Module-Name` should be avoided where possible as - based on my experience (others may have different experience) - it does more harm than good. I find it useful only during transition towards JPMS as a temporary thing (=should not be there for more than ~1-2 release(s))

**Comment by keilw** [comment]
Gee, how old is that thread?
@lukasj I agree that wherever possible true `module-info` should be used with `Automatic-Module-Name` as a fallback (e.g. where Multi-Release-JAR was used despite the mentioned caveats prior to Java 13) 

I have no idea where the Maven reference came from:
"adopt the following Maven conventions use dots in groupIds and dashes in artifactIds"
I was a key contributor and driving Spec Committee member of this EE 9.0 checklist:
https://docs.google.com/spreadsheets/d/1g8jYG0JixO3wzZkpeyU1LMIQRhbnZ76kGtdMFE8mieE/edit#gid=0

And it was decided back then to use the package name/groupId only and ignore the ".api", primarily because the [Naming Conventions](https://docs.oracle.com/javase/specs/jls/se16/html/jls-6.html#jls-6.1) in the Java SE Specification.
So the discussion or arguments here seems mostly outdated.

**Comment by lukasj** [comment]
I do see some food for #329 here, even though this is old and mostly out-dated now - everything but org.eclipse.persistence.jpa (which simply has too many dependencies to deal with) do have proper module descriptor now (in EE 9.1).

What is still relevant is expressed need for some guideline/set of recommendations for implementations to follow.

What I especially like is the proposal about using `legacy` classifier. It's elegant and I may have a use for it in one of the implementation projects soon (~within days).

The point I'm not sure about yet is "I'm especially worried about the current practices of reusing a specification's module name", since I'm sort of relying on this "reuse" on few places for some reasons and I'm not sure all of "my" reasons are historical only. One of them is probably related to the former concept of the _default implementation jar_ (ie mail, activation, jsonp).

> I have no idea where the Maven reference came from:
"adopt the following Maven conventions use dots in groupIds and dashes in artifactIds"

just search (Ctrl+F) on this page and you'll find it. It's in the 3rd bullet list of the issue description.

**Comment by keilw** [comment]
@lukasj There is of course a big caveat about using only module-info, see https://github.com/eclipse-ee4j/jakartaee-platform/issues/329#issuecomment-838659971

**Comment by keilw** [comment]
We applied all of this in Jakarta EE 9, so @kwsutter or others, is there a need to keep this open?
There may be slightly more if the likes of Jakarta REST also came up with more modules or "CDI Light" but I don't see this discusion to provide value and we solved the module naming in Jakarta EE 9 via the Google table (without even knowing this obviously low-prio ticket even existed ;-) so shouldn't it be closed while others like #329 are for EE10?

**Comment by starksm64** [comment]
So I was under the assumption that the https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules API_PACKAGE was the convention we had settled on for EE10. It has been pointed out that that document explicitly states "NOTE: This document does not yet specify requirements for Java platform module system names."

This needs to be corrected and this issue closed with the resolution and JakartaEE_Maven_Versioning_Rules updated.

**Comment by starksm64** [comment]
Ok, @lukasj pointed out this was captured in the https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee10/JakartaEE10ReleasePlan to be jakarta.<specName>, which may not the same as API_PACKAGE in general.

**Comment by starksm64** [comment]
All elements of this issue are captured in the following docs:

https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules
https://github.com/eclipse-ee4j/jakartaee-platform/wiki/JPMS_Naming_Rules
https://github.com/jakartaee/specification-committee/blob/master/names.adoc
