### ISSUE TITLE
Compatibility certification request for InforSuite Application Server for Full Platform

### ISSUE THREAD

**Issue by codff** [eclipse-ee4j/jakartaee-platform#306]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
[Shandong Cvicse Middleware Co.,Ltd.](http://www.inforbus.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
[InforSuite Application Server V10](http://www.inforbus.com/as.html)
- [x] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform, Full Platform 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip),SHA-256:14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965
- [x] Public URL of TCK Results Summary:<br/>
[TCK Results Summary](http://www.inforbus.com/InforsuiteAS/platform-tckresults/index1.html)
- [x] Any Additional Specification Certification Requirements:<br/>
Jakarta Injection
  [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
  `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
  Jakarta Contexts and Dependency Injection
  [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip)
  `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
  Jakarta Bean Validation
  [beanvalidation-tck-dist-2.0.5.tar.gz](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.tar.gz)
  `05afb564efaa6d893dbeb32fb614d6e2bd18f09cf76244386f3b377d725b14b8`
- [x] Java runtime used to run the implementation:<br/>
OracleJDK Java(TM) SE Runtime Environment (build 1.8.0_211)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
OS Version:CentOS Linux release 7.5.1804 (Core)
Database Version:10.10.2.0
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
+1 LGTM

**Comment by hantsy** [comment]
@codff Can you provide a link to your product?

**Comment by hantsy** [comment]
@ivargrimstad  This is the second product that declared passing the tck, but it did not provide a test-purpose product from their website.

I think Eclipse should consider to update the certification limitation to ensure the product to be certicated is existed.

**Comment by ivargrimstad** [comment]
@hantsy Providing a download link is optional according to the Jakarta EE TCK process, https://jakarta.ee/committees/specification/tckprocess/. I can bring it up on a spec committee call and see if this is something that should be changed or kept as is.

**Comment by TanjaObradovic** [comment]
@hantsy are you saying the the product link is missing on their website?
If so I see it here
![image](https://user-images.githubusercontent.com/40073121/108722676-68da2800-74f1-11eb-80be-61f257f92c14.png)

**Comment by hantsy** [comment]
> @hantsy are you saying the the product link is missing on their website?
> If so I see it here
> ![image](https://user-images.githubusercontent.com/40073121/108722676-68da2800-74f1-11eb-80be-61f257f92c14.png)
> 

Have you tried it?

**Comment by codff** [comment]
> @codff Can you provide a link to your product?
There is a button to apply for a trial version on our official website. You can get our product package in this way. The reason for not directly providing a download link is to prevent the product package from being obtained by criminals.This is not safe.

**Comment by codff** [comment]
> I did, but I did not pay attention on the content of the zip file
> ![image](https://user-images.githubusercontent.com/40073121/108734413-73022380-74fd-11eb-8263-65e6bcc47b23.png)

We did not directly provide the product download link, we think this is unsafe, and the product download link is optional in the above options, so this should not affect the product's compatibility certification, right?

**Comment by hantsy** [comment]
@ivargrimstad Personally, I hope Eclipse Foundation provides a more robust environment(such as cloud enviroment) to force the vendor to run the TCK tests and also do some code instruments (such as which application server it is based on, and the similiarity of some open-source application servers).

In the past 20 years, in China, as I know only  Huihoo JFox(open source)  and KingDee AS(commercial) have their team to build application servers. After Java EE 5, it seems Kingdee gave up its original AS, the latest version is based on GF. JFox was disconnected for years.

Currently, the application server certification is too easy to pass, just submitted the tck result, no one knows if there is a real product that existed.  For example,  I can download the source codes of GF, and rebrand it and pass the tck easily, it is a new product?

**Comment by hantsy** [comment]
@codff OK, you are right.

**Comment by codff** [comment]
@TanjaObradovic
Hi Tanja, 
Do I need other materials to submit? When will we pass the certification?

**Comment by edbratt** [comment]
The link to the TCK results on the TCK results page should just link to that file. The link through localhost won't work for anyone not logged into that computer. I'd recommend you change the URL to ./index.html (if that's what the file is actually called).
Could you please add TCK results for CDI, BV, and DI to the test results page?
Thank you.
(PS to answer your question about when certification is complete, see the [TCK process guide](https://jakarta.ee/committees/specification/tckprocess/). Look for the section titled Certification Resolution. If you have an urgent need, please let the Platform committer team know what time frame you are looking for.)

**Comment by codff** [comment]
@edbratt 
Hi edbratt,
I have modified the TCK result link according to your requirements. The link is "http://www.inforbus.com/InforsuiteAS/platform-tckresults/index1.html". I do have an urgent need, so I want to know the required time frame.Can you tell me or tell me who I should ask for?

**Comment by edbratt** [comment]
The link in your document at http://www.inforbus.com/InforsuiteAS/platform-tckresults/index1.html presents to me as localhost://InforsuiteAS/platform-tckresults/index1.html which won't work for anyone that clicks on it. Perhaps you cannot use a relative link for that server. I will notify the Platform committer team and see if we can get some reviewers. Without response, it will be approved 14 days after it is submitted.

**Comment by edbratt** [comment]
The SHA256 listed for the CDK TCK on the [results page](http://www.inforbus.com/InforsuiteAS/platform-tckresults/index1.html) doesn't match the SHA listed here in the issue. I believe that the SHA in this issue is correct. Please update the results page.

Unfortunately, the link in this issue to the TCK summary (above) no longer works for me. In the issue (in your summary), the link resolves to:

- http://www.inforbus.com/InforsuiteAS/platform-tckresults/

But this no longer returns a valid page. Perhaps just set them all to their full URL: 

- http://www.inforbus.com/InforsuiteAS/platform-tckresults/index1.html

I will send an e-mail to the platform committer discussion group to see if we can get this approved ahead of the 14 day "lazy consensus" target -- which would be Feb. 28th.

**Comment by kwsutter** [comment]
+1 to the various questions and concerns already posted about this Certification Request...

- The TCK results are not accessible via the link provided with this Issue.
- When I use the link provided by @edbratt, I'm able to get to some TCK results.  But, as reported elsewhere, the link for the TCK results on this page has a url with "localhost" in the name and,  of course, that will not resolve properly.
- Another comment from @edbratt that needs to be resolved... The SHA value on the TCK Results page does not match the one specified in this Issue.
- This issue references the additional testing for Debugging, but it's not listed on the TCK Results page.
- I would also challenge the idea that a download link is optional.  I agree that it currently states "(if applicable)", but we have been pretty consistent that a Compatible Implementation must be long lived and available via a download link or download page.  Otherwise, how does one know which version of the project actually passed the tests?  Not only today, but down the road?  All of the other CCRs that I have been reviewing in the past have been held to this standard.  I'm not sure why we think this is not required.  Thus, I agree with @hantsy.

I'm not ready to approve this request yet based on the above items.

**Comment by gerdogdu** [comment]
>  For example, I can download the source codes of GF, and rebrand it and pass the tck easily, it is a new product?

Actually, you can do this, at the moment nothing prevents you from doing this.

**Comment by gerdogdu** [comment]
> There is a button to apply for a trial version on our official website. You can get our product package in this way

@codff Can you please show us where to apply for the trial version? I did not find any button at your website to request a trial version.

**Comment by codff** [comment]
> > 在我们的官方网站上有一个按钮可以申请试用版。您可以通过这种方式获得我们的产品包装
> 
> @codff您能告诉我们在哪里申请试用版吗？我在您的网站上找不到任何按钮来请求试用版。

http://www.inforbus.com/contact.jsp On this page you can submit a trial version.

**Comment by codff** [comment]
> +1已针对此认证请求发布的各种问题和疑虑...
> 
> * 无法通过此问题随附的链接访问TCK结果。
> * 当我使用@edbratt提供的链接时，可以获得一些TCK结果。但是，正如在其他地方所报道的那样，此页面上TCK结果的链接的名称中包含带有“ localhost”的URL，当然，该URL无法正确解析。
> * @edbratt的另一条注释需要解决... TCK结果页面上的SHA值与本期中指定的不匹配。
> * 此问题引用了调试的其他测试，但未在“ TCK结果”页面上列出。
> * 我还会挑战下载链接是可选的想法。我同意当前声明为“（如果适用）”，但是我们一直认为兼容实现必须长期存在并且可以通过下载链接或下载页面获得。否则，如何知道该项目的哪个版本实际通过了测试？不仅是今天，而且还在路上？我过去审查过的所有其他CCR都保持了此标准。我不确定为什么我们认为这不是必需的。因此，我同意@hantsy。
> 
> 我尚未根据上述内容批准此请求。

I have understood these issues and I will modify them immediately.

**Comment by codff** [comment]
@kwsutter @edbratt 
Hi 
I have modified your questions, please click the link above to view the specific information.

**Comment by codff** [comment]
> > There is a button to apply for a trial version on our official website. You can get our product package in this way
> 
> @codff Can you please show us where to apply for the trial version? I did not find any button at your website to request a trial version.

http://www.inforbus.com/contact.jsp On this page you can submit a trial version.

**Comment by gerdogdu** [comment]
> http://www.inforbus.com/contact.jsp On this page you can submit a trial version.

It is impossible to request a trial from the page, [http://www.inforbus.com/contact.jsp](http://www.inforbus.com/contact.jsp)
It always gives us an error "Invalid Telephone number" and tried several phone format and nothing is working.

**Comment by codff** [comment]
> > http://www.inforbus.com/contact.jsp On this page you can submit a trial version.
> 
> It is impossible to request a trial from the page, http://www.inforbus.com/contact.jsp
> It always gives us an error "Invalid Telephone number" and tried several phone format and nothing works!

I have updated the product package to http://www.inforbus.com/as.html, please click the download button to download the product package.
![image](https://user-images.githubusercontent.com/79249422/109122565-c1285880-7783-11eb-8785-2496c4125896.png)

**Comment by hantsy** [comment]
@codff 

```bash
D:\appsvr\inforsuiteAS\bin>set JAVA_HOME=D:\jdk8

D:\appsvr\inforsuiteAS\bin>asadmin start-domain
Waiting for domain1 to start .Error starting domain domain1.
The server exited prematurely with exit code 0.
Command start-domain failed.
```

Java 8 and Java 11 got the same result, can not start the server. 

Obviously, this product is based on GF, but from the website and the docs(the two IMAGES in the download archive, I think for a descriptive document using PDF is better), I can not find any description to differentiate this product and GF.

As a developer, to experience this product, I can not find a page on your website or other locations to describe how to get started.

**Comment by codff** [comment]
@hantsy 
The reason for the startup failure is that there is no authorization file. Please provide me with your email address, and I can send the files you need to your email address.

**Comment by codff** [comment]
@hantsy 
The reason for the startup failure is that there is no authorization file.

**Comment by edbratt** [comment]
@hantsy all the changes I asked for are complete and appear satisfactory (download links and SHA256 codes). Thank you!

**Comment by kwsutter** [comment]
> @kwsutter @edbratt
> Hi
> I have modified your questions, please click the link above to view the specific information.

@codff Thanks for making the requested updates.  Based on the discussion on the Spec Community mailing list, I understand why a specific download link may not be applicable to all situations.  Thus, I won't hold that requirement against my approval.

It sounds like others participating on this Issue still have some questions about the availability of your implementation.  And, some questions about the documentation.  I'll let those conversations continue for a bit.

But, you have responded to my questions.  Thank you!

**Comment by codff** [comment]
@kwsutter 

I think this issue can be closed. 
Regarding the issues raised by hantsy, please @hantsy  leave your email or phone number. We can communicate about these issues at any time. There is no need to communicate under this issue.
Thank you!

**Comment by hantsy** [comment]
@kwsutter @edbratt Thanks for your effort to ensure there is a link to the real product. Now I know well what it is. 

Personally, I want to know if there are some exciting features in the implementation, for example,  the implementation of GF/Payara, WildFly, OpenLiberty are very different, thus we can compare the user experience between them. Obviously, after checking the content in the download archive, it will force me to treat it as another GF/Payara again. 

@codff I do not care about the purpose of getting the certification, of course, I also know well why some Chinese companies need such a certification because I also opened a company with my friends.   As an enterprise member of Jakarta EE,  you(if you stand for your company in Eclipse Foundation) can express Jakarta EE spec and knowledge in China, such as speaking on conf, organising meetups, sharing knowledge via WeChat public account etc,  and participate in the definition of the spec and implementation, let the whole world heard the voice from China.   That is the true meaningful activities you(your company) should have.

**Comment by ivargrimstad** [comment]
I think we're good to go on this one.
