### ISSUE TITLE
Reorganize the Platform repository

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#370]
As we are considering the Core Profile for Jakarta EE 10, and possibly allowing Profiles to be released independently of the Platform, the current organization of the Specification repository is difficult to maintain.  Also, if you add in ManagedBeans and the idea of possibly moving Common Annotations under the Platform umbrella, the current structure just gets more and more complicated.

Currently, all of these various specifications are housed under this umbrella directory structure:
https://github.com/eclipse-ee4j/jakartaee-platform/tree/master/specification/src/main/asciidoc

A single pom file is used to define the Specification Version for the Platform, Web Profile, and Core Profile (`<version>10-SNAPSHOT</version>`)  We also have a special pom file setting for processing the Managed Beans Spec Version (`<managedbean.version>2.1-SNAPSHOT</managedbean.version>`).

Another thing to consider is that eventually we should update the Specification build processing to be more automated via Jenkins jobs (https://github.com/eclipse-ee4j/jakartaee-platform/issues/113).

So, let's figure out a way to clean this up.  Not only to allow for easier releases of Core, Managed Beans, and Common Annotations (down the road) separate from the Platform.  But, also to allow for more automated build processes via Jenkins or the like.

My proposal is to create separate github repositories.  We could leave Platform and Web Profile together for now since they have always been tied at the hip.  But, if there is desire to break them apart as well, that would be fine.  All of these repositories would still be part of the Platform Project.  But, the maintenance of the Specs, tracking of Issues and PRs, releasing builds, etc would all be done via separate repositories.

I will also post this to the Platform mailing list to get some input.  If I get general agreement on this direction or some other suggestions are offered and agreed to, then I'm willing to do the reorganization in prep for Jakarta EE 10.

**Comment by aeiras** [comment]
HUGE +1, Kevin!

**Comment by starksm64** [comment]
Makes some sense, but there are common elements that need to be pulled out as discussed in #354 as well as new shared architectural guidelines from #3. Creating separate repositories seems like it would make it harder to include the common elements. Different Jenkins jobs could build the specs if each spec was a separate subproject with the comments elements in the parent source tree.

I can help investigate how to do this since the core profile has requirements to have the current specification tree restructured.

**Comment by dblevins** [comment]
I'm definitely pro for splitting out Managed Beans.  I'm still very skeptical and not quite on board with the idea of the Platform, Web Profile and Core being released separately.  I've so far not been able to get my head around it.  My preference would be to keep those three together for the time being.

**Comment by ivargrimstad** [comment]
I agree. The first step should be to split out managed beans into a separate repository.
The next steps should be to evaluate the implications, such as common elements, to see which changes that would be required to be able to split the platform and profile specs into separate repositories as well. If that is what we want.

**Comment by kwsutter** [comment]
Thanks for the input.  I think we're all on the same page regarding Managed Beans being in a separate repo, so I'll start with that one.  As we learn more about the direction of the Core Profile and it's relationship to Platform (and Web Profile), then we can adjust that later.

**Comment by aeiras** [comment]
@kwsutter will that repo live under the Jakarta EE group? 

Last summer the Specification cmtee voted to clean up, moved the Jakarta EE repos from the EE4J repo to its own Group under the Jakarta space. I wonder if that will start to happen with current work? 

Cheers,

**Comment by kwsutter** [comment]
@aeiras This new repo will be created under the same eclipse-ee4j organization in github.  When it's decided that we will separate the Specs/APIs/TCKs from the Implementations, then that would be done all at once to avoid confusion.  Thanks!

**Comment by aeiras** [comment]
Gotcha, Kevin. Thanks for the response. 💙

I asked out of concern for what currently is. 
example, we are behind the creation of the contributors cards feature that pulls contributors commits & prs on each release. 
it has been challenging (but not impossible) to select - limit the exact repos that are relevant under each release. With only 2 under our belt since the feature was created, the sooner the repos are prioritized under the Jakarta EE Repo de better for selection without anyone having to police where the data comes from. 

With Ivar & Cesar, we actually spent time figuring out how many projects & how many specs when into the EE 9.1 release as well. Why? Bc the information is not clearly available nor consumable. 

Lastly, APIs should be independent of any implementation during development to ensure across the board neutrality. 

It is all about the patent - Repo. ⚖️

I hope this helps everyone in this thread understand why I zoom out to say +1 on Repo prioritizing.

**Comment by kwsutter** [comment]
Based on the discussions in this Issue, I don't think we're ready to split the Platform from the Web Profile -- at least, not into separate repositories and build processes.  We have completed the separating of the Managed Beans build process away from the Platform and Web Profile via the PRs mentioned in https://github.com/eclipse-ee4j/jakartaee-platform/issues/370#issuecomment-858718622.  Since we have [other Issues](https://github.com/eclipse-ee4j/jakartaee-platform/issues/370#issuecomment-854279188) opened to address the Core Profile and possibly sharing content with the Platform and/or Web Profile, I think this particular Issue has run its course.  I will close it now and we can either re-open or create new Issues as needed.
