### ISSUE TITLE
Define Theme for Jakarta EE.Next

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#5]
We need to define a theme for the Jakarta EE 9 platform. Some combination of:
- Propose a theme and encourage the specification projects to provide specs supporting it 
(top-down)
- Extract a theme from the planned changes in the individual specification projects 
(bottom-up)

### Samples from previous Java EE releases
- Java EE 8 - Modernization & Simplification
- Java EE 7 - Developer Productivity, HTML5, Meeting Enterprise Demands
- Java EE 6 - Extensibility and Profiles
- Java EE 5 - Ease of Use

**Comment by keilw** [comment]
Anything else than "Move to the Cloud" or similar? ;-)

**Comment by gilbertoca** [comment]
A good one, the [Integration with CDI and Config](https://www.eclipse.org/ee4j/direction.php#integration-with-cdi-and-config). I mean, an easy and simple configuration (smoothness).

**Comment by ivargrimstad** [comment]
Can anyone involved in the Expert Group for any of the Java EE platform releases provide some input about how and when the theme was chosen?

**Comment by keilw** [comment]
I don't recall the Java EE EG was ever asked about that. And I've been in the Umbrella EG since Java EE 6. It was likely Oracle or its marketing team picking such slogans.

**Comment by bshannon** [comment]
> Can anyone involved in the Expert Group for any of the Java EE platform releases provide some input about how and when the theme was chosen?

At Oracle we would start thinking about this as the current release was wrapping up,
but we typically didn't start talking about it in public until well after the current release
to avoid confusing the message for the current release.  It was usually more than a
year from completing the current release to submitting a JSR for the next release.

The theme was a synthesis of the feedback we had gotten while producing the current
release, as well as our own vision about where the platform should go.  We also did
some community surveys to collect more feedback that we used to guide the next release.
All of this was moderated by the resources we knew would be available for the next release;
there was no sense in proposing something that we couldn't deliver.

To see Oracle's vision for where the platform should go after Java EE 8, see our presentations
at JavaOne from several years ago when we were still planning a Java EE 9.

**Comment by anthonyvdotbe** [comment]
Imho, support for Java modules is paramount. How about "Alignment"? This would refer to:
- Java SE alignment
- CDI alignment (see e.g. [Arjan Tijms'](https://blog.payara.fish/jakarta-ee-9-2019-outlook) and [Richard Monson-Haefel's](https://www.tomitribe.com/blog/jms-3-0-get-involved/) blog posts)

Java SE alignment would involve:
- modularity, which was the [initial plan](https://github.com/eclipse-ee4j/jakartaee-platform/issues/1#issuecomment-453285474) for Java EE 9 and is mentioned in the [technical direction](https://www.eclipse.org/ee4j/direction.php#embrace-jpms). This would involve things like (I'm sure a lot of thought has been put into this already, just adding my 2 cents):
  - defining a module graph, with aggregator modules for profiles
  - turning all Jakarta EE specifications into modular JARs (not just automatic modules) and, ideally, requiring the implementations of certain specifications to be modular JARs as well (esp. those that are depended upon by MicroProfile)
  - thinking about the integrations between specification/implementation/application modules, e.g.
    - adopting `java.util.ServiceLoader` & the uses/provides mechanism
    - adopting the "app module hands out a MethodHandles.Lookup object to the spec module"-strategy, instead of the current "server uses core reflection on the app"-strategy
  - rethinking deployment & packagings such as .ear/.war
  - reviewing Java SE dependencies. For example, if all dependencies on the java.beans package could be eliminated (e.g. `javax.el` has a couple references to `java.beans.FeatureDescriptor` in its API), it would be possible to build custom runtimes with jlink and exclude the whole `java.desktop` module. (I assume this would have to be done in Jakarta EE 10 at least, with a `@Deprecated(forRemoval=true)` being added to the APIs in Jakarta EE 9)
- "Reactive". Since Java SE 9, Reactive Streams has been integrated as `java.util.concurrent.Flow`. [This](https://www.eclipse.org/lists/ee4j-community/msg01141.html) e-mail from James Roper sums it up nicely. There's also been a lot of activity around this in MicroProfile recently, with e.g. [Reactive Streams Operators](https://github.com/eclipse/microprofile-reactive-streams-operators) and [Reactive Messaging](https://github.com/eclipse/microprofile-reactive-messaging) (as [already noted](https://github.com/eclipse-ee4j/jms-api/issues/192)).
- API alignment:
  - adopting/integrating the new naming conventions. Since Java SE 9, new APIs no longer use the JavaBeans naming conventions. Basically, the `get/set/is` prefixes have been dropped. So should new APIs in Jakarta EE do the same? Either way, specifications like Expression Language should prepare for this (or maybe EL already has a built-in mechanism for custom naming schemes?)
  - deprecating legacy API signatures (possibly with `forRemoval=true`) in favor of new APIs:
    - java.util.Vector/Hashtable et al. -> java.util.List/Map
    - java.util.Date et al. -> java.time.*
    - java.io.File et al. -> java.nio.file.*
    - where appropriate: arrays/collections -> java.util.stream
    - where appropriate: null-returning methods -> Optional
    - ...

**Comment by kwsutter** [comment]
The [content and "theme" for Jakarta EE 9](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan) has been decided.  I'm going to close this Issue.
