### ISSUE TITLE
Verify the web profile and full platform staged api artifacts before ballot

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#521]
The web profile and platform api artifacts may be missing the latest service releases. We need to update these before going to final ballot.

**Comment by JanWesterkamp-iJUG** [comment]
Concurrency needs to ba updated from 3.0.0 to 3.0.1.

**Comment by JanWesterkamp-iJUG** [comment]
Validation version needs to be updated from 3.0.1 to 3.0.2 as well.

**Comment by JanWesterkamp-iJUG** [comment]
I created a PR as mentioned in the Platform Call to fix the (yet available) API versions: https://github.com/eclipse-ee4j/jakartaee-api/pull/132

But there are still findings, like the definition of CP specific versions, that are not used - I would suggest, that they should be part of the comment saying that they may deviate (but in fact did not).
Some definitions are missing or are reused:

- CP EL version is missing
- separate definition of Model Lang is missing - CDI is used
- separate definition of WebSocket Client is missing - WebSocket is used

I would suggest to add the CP specific versions to the comment and reoder the CP related definitons from WP to CP.
I also could reorder the version definitions and dependencies according to the "waves" or dependency levels (lowest first) - but a build with the last changes would help doing that, because it cleans up a lot of duplicate dependencies in the graphs.

While waiting for the last fixes in the Web Profile implementations at the moment, we could thing about fixing the dependency definitions in at least Interceptor API (-> 2.1.1) and CDI API (-> 4.0.2 and Model Lang API?), to have a clean Core Profile right from the beginning.

The last (potential) finding is the transitive dependency from the optional XML Bind in CP to Activation - should we reference the (optional) dependency directly here too?

@starksm64 can you review and merge the PR and trigger a build of it afterwards, please?
When you ping me, I can create updated dependency analysis and we can have a look on the results to discuss the remaining topics above.
Meanwhile, I also pushed my changes to the depenency analysis demo project and Dirk merged them already - so you can run them by yourself easily, if you like.

**Comment by JanWesterkamp-iJUG** [comment]
> Validation version needs to be updated from 3.0.1 or 3.0.2 as well.

This deviation came form Faces 4.0.1, which has a dependency to Validation API 3.0.2.
But note, Validation TCKs last version is still 3.0.1, but this TCK version has a lot of outdated and creapy dependencies like Milestone and RC versions too:

<properties>
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>

<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<validation.api.version>3.0.0</validation.api.version>

<license.file>license.txt</license.file>

<hibernate.validator.version>7.0.0.Alpha5</hibernate.validator.version>
<testng.version>6.14.3</testng.version>
<assertj-core.version>3.7.0</assertj-core.version>
<jakarta.cdi.version>3.0.0-M3</jakarta.cdi.version>
<jakarta.el.version>4.0.0-RC1</jakarta.el.version>
<jakarta.interceptor.version>2.0.0-RC2</jakarta.interceptor.version>
<jakarta.ejb.version>4.0.0-RC1</jakarta.ejb.version>
<jakarta.annotation.version>2.0.0-RC1</jakarta.annotation.version>
<jboss.test.audit.version>1.1.3.Final</jboss.test.audit.version>
<arquillian.version>1.7.0.Alpha2</arquillian.version>
<shrinkwrap.descriptors.version>2.0.0</shrinkwrap.descriptors.version>

<hibernate-asciidoctor-theme.version>1.0.1.Final</hibernate-asciidoctor-theme.version>
<asciidoctor-maven-plugin.version>1.5.3</asciidoctor-maven-plugin.version>
<jruby.version>1.7.26</jruby.version>
<asciidoctorj.version>1.5.4.1</asciidoctorj.version>
<asciidoctorj-pdf.version>1.5.0-alpha.11</asciidoctorj-pdf.version>
<beanvalidation-tck-parent.basedir>${project.basedir}</beanvalidation-tck-parent.basedir>

<com.puppycrawl.tools.version>8.29</com.puppycrawl.tools.version>
</properties>

@starksm64, @scottmarlow That means for me, (in this case) the component spec test environment deviates significantly from the umbrella spec environment (not only regarding it's service release version) and this may lead to different test results (!) - and so generates a high potential for late supprises in the Platform/Profile releases...
Should we create a new Validation TCK (Service?) release here?
How is it ensured, that the CI for the component spec will rerun the changed component spec TCK?

@starksm64 some of these aspects may be delegated to the (Platform) retrospective and might be addressed in a Jakarta Next release - they are a little bit resulting from a discussion in the last TCK call too... ;-)

**Comment by JanWesterkamp-iJUG** [comment]
Another (minor) aspect, that should be solved is the occurence of test(-framework) dependencies inside API artifacts at all and their version deviations.

Do we want to address them too? With the current or the next release?
My suggestion would be to at least address the version deviations as much as possible as soon as possible. Some of the occurences could be easily removed from the API when they are resulting from a (maven) multiple module project setup with dependency definitions in the parent but actual use only in the TCK submodule (i.e. I fixed that in Concurrent 3.0.1).

**Comment by starksm64** [comment]
@JanWesterkamp-iJUG The API jar build was updated last night

**Comment by JanWesterkamp-iJUG** [comment]
@starksm64 many thanks, I updated and commented the analysis here:
https://github.com/eclipse-ee4j/jakartaee-api/issues/125#issuecomment-1210611757
