### ISSUE TITLE
Update Scope Statement for Jakarta EE Platform Specification Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#8]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance 

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by ivargrimstad** [comment]
## Suggestion
Jakarta EE Platform aggregates Jakarta EE specifications, defines platform profiles and sets the overall direction of the platform to ensure a coherent platform based on the other Jakarta EE specifications.

**Comment by mkarg** [comment]
# Counter Proposal

**Jakarta EE** is an *umbrella specification* for a set of profiles of otherwise standalone APIs.

**Comment by ivargrimstad** [comment]
I think it would be beneficial if the scope of the platform spec also included the responsibility for cross-cutting concerns and ensuring some sort of direction. E.g. ensure that we don't end up with 25 different injection mechanisms or standards for configuration.

**Comment by mkarg** [comment]
@ivargrimstad +1 for cross-cutting concerns, but not for the price of giving up the self-governance of the APIs. As I said many times, in the end, it is the committers that do the work finally, so they have to propose a common proposal instead of waiting for a separate umbrella team doing that work

**Comment by ivargrimstad** [comment]
@mkarg Absolutely! I think we are on the same page here. Just need to find the perfect wording to allow for self-governing projects as well as some means of encouraging communication across project borders to benefit the platform the most.

**Comment by mkarg** [comment]
Well, not voting on proposed EE committers was possibly the wrong communication to get API committers into the boat.

**Comment by ederks85** [comment]
Jakarta EE provides a feature-rich set of specifications that empower developers in creating cloud-native, Java-based enterprise applications. It's goal is to provide an open-source platform that is powered by community input in order to provide the optimal experience in developing and running enterprise applications in the cloud.

**Comment by mkarg** [comment]
@ederks85 That sound more like a personal vision as none of that is currently true. Neither is Jakarta EE cloud-native, nor is it driven by community input, and the experience of Jakarta EE in the cloud is "clumsy". What you describe is Microprofile, not Jakarta.

**Comment by ederks85** [comment]
@mkarg "The future of cloud-native Java" is how the platform is currently marketed, so it is not just my personal vision. How you interpret "cloud-native", is a matter of opinion. I have my own opinion about that which I will explain in conference talks in the near future. But I agree that MicroProfile is the key to make that happen.

Therefore I was merely providing a suggestion about how I feel about the platform and how to describe it with the future view that is being defined for it. If you disagree with it, or feel that it isn't accurate, feel free to discard it.

**Comment by waynebeaton** [comment]
What in a general sense does the Jakarta EE Platform specify? It's a platform that does what, specifically?

It's worth noting that the Jakarta EE Platform **project** actually includes multiple specifications, including Web Profile. How is Web Profile different from the Full Profile?

> Jakarta EE is an umbrella specification for a set of profiles of otherwise standalone APIs.

How is Full Profile different from Web Profile?

@ederks85 is probably close with something like this:

> The Jakarta EE platform provides a feature-rich set of specifications that empower developers in creating Java-based enterprise applications. 

I'm thinking that the scope includes terms like "application server", "distributed", "integrated", and "scalable".

**Comment by bshannon** [comment]
The Web Profile is a subset of the full platform that includes specifications
needed by web-focused applications.  Specifications primarily used by
back-end enterprise applications are not included.

**Comment by mkarg** [comment]
> What in a general sense does the Jakarta EE Platform specify? It's a platform that does what, specifically?

Actually the platform *only* provides *lists* (called profiles) of otherwise independ specifications, and clarifies some cross-cutting concerns. There is no *standalone* "Jakarta EE API" in fact. "Jakarta EE API" is just the aggregate of the externally developed APIs like JPA and CDI etc., which both live outside of the platform, but are *referenced* by this list.

> > The Jakarta EE platform provides a feature-rich set of specifications that empower developers in creating Java-based enterprise applications.

The Platform project is *not* providing any API on its own. It is *just* a list of references plus some clarifications on cross-cutting concerns.

> I'm thinking that the scope includes terms like "application server", "distributed", "integrated", and "scalable".

Actually this would be wrong, as the architectural aspect of the mentioned APIs is *not* constrained in any way. You could even implement it as a small bootstrapper for embedded devices or wrap it around your existing cloud offering, without distributing anything or having an application server in the boat at all.

**Comment by keilw** [comment]
While it hits the point I'm not sure if  "application server" would go well because many technologies and frameworks that call themselves "serverless" also use aspects of Jakarta EE.

**Comment by anthonyvdotbe** [comment]
> The Platform project is _not_ providing any API on its own. It is _just_ a list of references plus some clarifications on cross-cutting concerns.

In my view, the Platform provides an aggregate API, analog to the `java.se` module in Java SE. In other words, I consider it irrelevant whether the Platform's APIs are provided by delegation to other specifications or by specifying them itself (i.e. `requires transitive` vs. `exports` in module speak).
Also, "clarifications" is an understatement, imho: the Platform specifies additional requirements & integrations, certain deployment descriptors (e.g. the `Common Java EE XML Schema`, which is depended upon by other specifications), etc. in order to provide developers with "a consistent, integrated whole that is more than the sum of its parts", i.e. a platform.

**Comment by bshannon** [comment]
> Actually the platform only provides lists (called profiles) of otherwise independ specifications, and clarifies some cross-cutting concerns.

While it's true that the platform does not define any new Java APIs of its own, it does do more
than described above.  It defines a deployment model.  It defines the JNDI namespace and
associated requirements.  It defines the packaging model for "ear" files and application clients.

**Comment by waynebeaton** [comment]
It occurred to me that there are, I think, three different specifications that fall under this project (Full Profile, Web Profile, and Managed Beans). Is this accurate? Have I missed something?

Assuming that I'm correct. the project scope is something along the lines of "The Jakarta EE Platform project provides the specification documents ~~, API, and TCK~~ for the Full Profile, Web Profile, and Managed Beans specifications." I assume that I'm a little off base on including the API and TCK; I tend to think of these statements as aspirational. However, in the case of the Full and Web Profiles at least, we have a whole project that exists for their TCK, so maybe there's no aspiration to have the TCK here. I may be mumbling at this point.

I believe that leaves us with a need to have scope statements for each of these specifications.

The Jakarta EE Platform Full Profile defines the aggregation and integration of the full collection of Jakarta EE specifications.

The Jakarta EE Platform Web Profile defines the aggregation and integration of the subset of Jakarta EE specifications related to the development of web applications.

The Jakarta Managed Beans specification defines a set of basic services for container-managed objects
with minimal requirements, otherwise known under the acronym “POJOs” (Plain Old Java Objects). 

Thoughts?

**Comment by bshannon** [comment]
Yes, three specs, currently in one spec repository.

The API jar files and javadocs for the platform are produced here so API should be included.

If/when the TCK project is broken up, the pieces that remain for the platform could be moved here,
abandoning the existing jakartaee-tck project.  So, I would keep TCK in the list.

The spec scope statements look fine.

**Comment by waynebeaton** [comment]
By lazy consensus, I declare victory with this scope statement:

> The Jakarta EE Platform project provides the specification document, and related technical artifacts for the Jakarta EE Platform Full Profile, Jakarta EE Platform Web Profile, and Jakarta Managed Beans Specifications.
> 
> The Jakarta EE Platform Full Profile defines the aggregation and integration of the full collection of Jakarta EE specifications.
> 
> The Jakarta EE Platform Web Profile defines the aggregation and integration of the subset of Jakarta EE specifications related to the development of web applications.
> 
> The Jakarta Managed Beans specification defines a set of basic services for container-managed objects with minimal requirements, otherwise known under the acronym “POJOs” (Plain Old Java Objects).
